### ISSUE TITLE
Data Schema

### ISSUE THREAD

**Issue by mhughes27** [rlyons21/To-Do-List#12]
[0] Complete or incomplete (C or I)
[1] Bob - assigned or unassigned  (A or -)
[2] Mary - assigned or unassigned (A or -)
[3] Joe - assigned or unassigned (A or -)
[4] Lisa - assigned or unassigned (A or -)
[5] through [10] could be used for larger families
[11+] Tasks to be completed

Examples:
"IA---------Clean your room"         (Bob clean your room)
"C-A--------Sweep the kitchen"   (Mary swept the kitchen)
"I----------Mow the Lawn"            (unassigned mow the lawn)
"C---A------Empty the dishwasher"   (Lisa empty the dishwasher)

**Comment by sumeetjain** [comment]
I know I said this app is for one particular family, but I should have been clearer. It's for one particular family, but it could be used by _any_ family. So if the Johnsons use it, there'll be a Bob, Mary, Joe, and Lisa. But if the Guptas use it, then there'll be other family members and names. And there might be fewer or more members, which would mess with the strictness of 5+ being for the task title.

So consider how you would increase the flexibility of this schema. Also remember that we decided during our checkin to only assign one person to each task, for now.

**Comment by mikeducey** [comment]
There are now ten dashes for ten family members, which should accommodate larger family sizes.  If we need a data set for families larger than ten, this will have to be updated further.

**Comment by sumeetjain** [comment]
Try something like this instead:

`C|Bob|Clean kitchen`

The use a delimiter will make the data much more flexible right away.

**Comment by mikeducey** [comment]
This has been used, and used well!
